### ISSUE TITLE
Button not disabled on browser startup

### ISSUE THREAD

**Issue by crustyturd** [tarakbumba/restore-tabs-button-for-palemoon#1]
Clearing unclosed tabs disables toolbar button. However, on browser restart, button is no longer disabled, even though there are no unclosed tabs.

Palemoon 29.2.0

**Comment by crustyturd** [comment]
I meant to say "even though there are no 'closed' tabs."

**Comment by crustyturd** [comment]
Should the button not also be in disabled state after all closed tabs have been reopened?

**Comment by tarakbumba** [comment]
No. It's not like that. Even original add-on, Undo Closed Tabs Button add-on, behaves same as your description. It's not a buggy behaviour, clicking on button doesn't cause an issue. Also you can see that in translations, there's a label set for this behaviour: "No closed tabs to undo".

**Comment by tarakbumba** [comment]
OK. I think I've found the culprit. There was a function which is removed due to another issue. I re-added it and modified for this fork. It should be ok. Would you mind to test version 1.3beta1 and report back?

**Comment by tarakbumba** [comment]
I released a new 1.3beta3 release today. This release should also fix a left-over issue from original code and re-introduced by previous beta that extension tries to open non-existent welcoming web page upon extension install/upgrade. Please test this 1.3beta3 and report back?
